GET http://localhost:3000/graduates

###

GET http://localhost:3000/graduates/5e3b8d6c3b6e179644328ed7

###
POST http://localhost:3000/graduates
Content-Type: application/json

{
        "name":"John",
        "lastName":"Smith",
        "jobTitle":"Homie",
        "companyName":"CareerDev",
        "keySkills":"Coding",
        "linkedIn":"johnLinkedIn",
        "gitHub":"dddndkdkd",
        "twitterName":"PreasttyMofoTItus"
}


###
DELETE  http://localhost:3000/graduates/5e3b66026062bd94e8c2382f


###
PATCH http://localhost:3000/graduates/5e3b744136bf4295b60149b4
Content-Type: application/json

{
    "name":"TEEEEEEZUS"
}